import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// 1. Take control of the page immediately after activation
self.skipWaiting();
clientsClaim();

// 2. Clean up old caches from previous versions
cleanupOutdatedCaches();

// 3. Precache all assets generated by the build process
// (This array is populated automatically by vite-plugin-pwa during build)
precacheAndRoute(self.__WB_MANIFEST);

// 4. Cache Google Fonts (StaleWhileRevalidate)
// Loads from cache for speed, updates in background
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20 }),
    ],
  })
);

// 5. Cache Tarot Card Images & Static Assets (CacheFirst)
// These images don't change often, so serve from cache
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100, // Keep up to 100 images
        maxAgeSeconds: 30 * 24 * 60 * 60, // Cache for 30 Days
      }),
    ],
  })
);

// 6. API Calls to OpenRouter (NetworkOnly)
// AI readings must ALWAYS be fresh. Never cache predictions.
registerRoute(
  ({ url }) => url.href.includes('openrouter.ai/api'),
  new NetworkOnly()
);

// 7. Fallback for other API calls (NetworkFirst)
// Try network, if offline, try cache
registerRoute(
  ({ url }) => url.pathname.startsWith('/api'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// 8. Handle Offline Fallback (Optional)
// If navigation fails, we could serve a specific offline.html here
// But since it's an SPA, the index.html is precached.
